### ISSUE TITLE
Shared envs across packages

### ISSUE THREAD

**Issue by inca** [ubio/node-framework#53]
Our current approach to managing type-safe env variables seems to be limited to a single package/repo scenario, i.e. whereby each application maintains a single `Env` class that lists all the environment variables and is injected to the classes of that application.

Despite being handy, this approach fails to scale to multiple applications sharing the same classes that need to be configured via env variables. We also [have this problem already](https://github.com/ubio/node-framework/blob/fcfe99d6b267f98e9d8d33a086a3ef51b2369889/src/main/env.ts#L55) with `FrameworkEnv` declaring shared bits of environment for shared classes provided by the framework.

## Requirements

We need to come up with a way to organise environment variables management with following requirements:

- **reusability:** any class configured via environment should be easily extractable into a shared library, so that other applications can use it
- **type-safety:** each configuration property should support basic types (at very least string, number, boolean) with TypeScript support; `process.env` values should be automatically coerced to expected type
- **decentralization:** applications that don't _actually_ use any particular environment variable should not require it in their runtimes
- **early fail:** if a required env variable is missing, application should alert about this as early as possible, preferably at startup
- **self-documenting:** it should be possible to understand which env variables are supported by an application, either by reading the source code or by some tooling (e.g. CLI to generate `.env.example` or to list env variables).

## Option A: base classes + inheritance

It is possible to maintain a chain of inheritance, e.g. 

```
FrameworkEnv (Node Framework) <-- SharedEnv (Shared Lib) <-- AppEnv (End Application)
```

This approach satisfies reusability and type-safety criteria (with additional parsing utils, since all env variables are class properties and can be strongly typed). Decentralization criterion is not met, because each app would have to consume all envs from `FrameworkEnv` and `SharedEnv`, thus it's not possible to selectively consume classes from a shared library without having to also configure them. Self-documentation criterion is more-or-less met, given that one only have to look in three different files to figure out what to configure (but one can argue that it's not an optimal experience).

## Option B: static env declarations + runtime resolution

This approach is actively used in Autopilot. The env variables are first [statically declared](https://github.com/automationcloud/autopilot/blob/9eb93c79ba9dd4ea401f1e2c5ecfc6b5e5e8aed8/packages/engine/src/main/services/browser.ts#L29-L32) and then [consumed at runtime](https://github.com/automationcloud/autopilot/blob/9eb93c79ba9dd4ea401f1e2c5ecfc6b5e5e8aed8/packages/engine/src/main/services/browser.ts#L62-L65) by reading the values from `Configuration` instance.

This approach was developed with decentralization in mind (Autopilot code was split across different packages early on). It meets most of the requirements (it's decentralized, type-safe, allows for easy reusability and self-documenting with some tooling support), and allows one to implement a custom configuration backend (for example, Autopilot Electron app does not support `process.env` and reads the configuration from user data stored in file system).

Among the downsides:

- "early fail" is not met, there is no ability to detect if configuration is missing until the resolution stage (this was specifically a requirement for Autopilot which supports extensions and should not fail like that)
- additional tooling is required to list all supported env variables; even more tooling and/or considerations is required to figure out which env variables are actually in use (v.s. just listing all of them)
- sometimes multiple classes may need to reference a single env variable, in which case it's not immediately obvious where to put it

**Comment by inca** [comment]
So so so, I did a bunch of experiments today (mostly because this tiny thing is blocking my progress with monorepo setup). I was mostly trying to adapt the Option B used in Autopilot, but wasn't too happy about various trade-offs (both in syntax and in unmet requirements).

At the end I decided to try something completely different and I think I might be onto something.

In a nutshell, I plan to introduce a property decorator that will replace said property in runtime with a getter. The getter will resolve the configuration value using `Configuration` instance attached to the class.

Here's a contrived example:

![image](https://user-images.githubusercontent.com/118196/121232133-ef94f400-c899-11eb-8eae-364ff171e35f.png)

In this example `FOO` member becomes a getter, so when you actually run this, it will print `>>>>>>>>> resolved FOO!!!!11`.

Doing it this way is pretty succinct (even design:type is inferred, so no ugly `stringConfig`, `numberConfig`, etc are necessary) and also maintains good abstractions (e.g. it's possible to query `Configuration` directly, and have multiple configuration backends implemented, `process.env` being one of them). Also, because it's decorator based, it's possible to understand in runtime which configs are used (provided that I'll be able to obtain the bindings from Inversify container).

Will try and wrap up the PR tomorrow.

**Comment by kyungeunni** [comment]
Looks good! one thing that comes to my mind is that we must remember to inject the `Configuration` when we are to use `@config` decorators which is not obvious at the first glance. Also I presume we will need to use the specific property name that config decorator expect (line 19).

**Comment by inca** [comment]
That's what the `Configurable` interface is for. It prevents you (at compile time) from being able to use `@config` decorator on classes that don't have `config: Config` property.

**Comment by inca** [comment]
So I've [created a PR](https://github.com/ubio/node-framework/pull/54) with the above ideas implemented. Aside from some additional tooling I consider it ready.

It meets the following criteria:

- **Fail-fast:** given `Container` instance it is possible to query the configs required for all the services bound to it; and given `Config` instance it's possible to check whether all requirements are satisfied; this is possible _without_ waiting for configs to be queried (e.g. I can add an `assertConfigs` method to `Application`, so that it can be called inside an entry point)
- **Decentralized:** you can move classes around how you want, e.g. move from app to shared package or the other way around — it will just work
- **Self-documenting:** key, type and default value are available at metadata level, so it's possible to access them with tools; once `.env.example` will be generated it will be even smoother experience (we can even re-generate it automatically on pre-commit or similar to keep it up-to-date)

That being said, it's not **perfect**:

- My biggest grievance is actually the syntax — it almost spells backwards with `default` being an argument inside decorator, preceding everything else.

    ```ts
    @config({ default: 8080 }) PORT!: number;
    ```

- Aside from that, type safety is not perfect: it's not possible to infer the property type `number` to constrain the type of decorator (afaik), so the following will still compile (and is parsed additionally at runtime):

    ```ts
    @config({ default: '8080' }) PORT!: number;
    ```

    In my opinion it's not a biggie, since we only allow `string`, `number` and `boolean` and don't allow quirks like NaN — so the parsing rules are adequate.
    
- The exclamation sign `!` is okay-ish, given the conventionalist nature of this feature, but still hints at magic. Remove the decorator — and you're in trouble (but many, many other concepts also fail with that same reasoning).

- Finally, I can't do anything about those shortcomings, because they are based on JavaScript (mostly) + TypeScript (to lesser extent) limitations.

/cc @kyungeunni @nicck @TobiaszCudnik  I would appreciate any thoughts/feedback/suggestions before shipping this as the next major 🙏

**Comment by kyungeunni** [comment]
Awesome 🎖️ I like the fact that we can define how to resolve the environment configs by defining another class inheriting `Config`. (especially frontend applications in mind). One minor thought about `config` - it's injected solely for config decorators and it could be a bit confusing, but not a biggy(also I guess it will be enforced by TS ?). Also, can we add a safeguard around `resolve` method which we can prevent config name collision?

**Comment by inca** [comment]
Here's what roughly happens if you don't include `config: Config` (also note it should be `public` I think it's good enough).

![4d9c4d1c9962bb17da40179fdf033321](https://user-images.githubusercontent.com/118196/121879440-87209980-cd15-11eb-9dc6-c6c6796e11c1.gif)

Sorry didn't really catch that bit about `resolve` — do you mean to disallow duplicate env variables? If so, I don't think it's necessary, because configs aren't really "owned" by a class. The only reason I store them in class metadata is to be able to obtain the "actually used" configs to generate `.env` (it'll be in a separate PR).
