### ISSUE TITLE
`instance` label used by pushgateway shouldn't be unique per every cron job

### ISSUE THREAD

**Issue by kyungeunni** [ubio/node-framework#68]
Pushgateway uses `process.env.HOST_NAME` as instance label when pushing the metrics.
https://github.com/ubio/node-framework/blob/main/src/main/metrics/push-gateway.ts#L37

Kubernetes Container environment expose pod name as hostname which means every cron job pod will use different name for `instance` label.
This caused quite an impact on performance so the instance value needs to be updated to have the same value per Cron Job or Application.

Proposed solution is for the each application to set the `instance` value.

**Comment by inca** [comment]
Can we infer it from `package.json` (e.g. by reading from `process.cwd()`)?

**Comment by kyungeunni** [comment]
That info (package name) is used for `job` label. Maybe shall we omit the `instance` label if it's not so important? according to the [doc](https://github.com/prometheus/pushgateway#about-the-job-and-instance-labels) it is ok to not have instance label.
